src/MicroweberPackages/Tax/routes/admin.php
<?php


Route::prefix(ADMIN_PREFIX)->namespace('\MicroweberPackages\Tax\Http\Controllers\Admin')->group(function () {

    Route::resource('tax-types', 'TaxTypeController');

});

src/MicroweberPackages/Tax/Http/Controllers/Admin/TaxTypeController.php
<?php
namespace MicroweberPackages\Tax\Http\Controllers\Admin;

use MicroweberPackages\App\Http\Controllers\AdminController;
use MicroweberPackages\Tax\Tax;
use MicroweberPackages\Tax\TaxType;
use MicroweberPackages\Tax\User;
use MicroweberPackages\Tax\Http\Requests\TaxTypeRequest;
use Illuminate\Http\Request;

class TaxTypeController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $taxTypes = TaxType::whereCompany($request->header('company'))
            ->latest()
            ->get();

        return $this->view('tax::admin.taxes.index', [
            'taxTypes' => $taxTypes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->view('tax::admin.taxes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaxTypeRequest $request)
    {
        $taxType = new TaxType();
        $taxType->name = $request->name;
        $taxType->type = $request->type;
        $taxType->rate = $request->rate;
        $taxType->description = $request->description;
        if ($request->has('compound_tax')) {
            $taxType->compound_tax = $request->compound_tax;
        }
        $taxType->company_id = $request->header('company');
        $taxType->save();

        return $this->view('tax::admin.taxes.edit',[
            'taxType' => $taxType,
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \MicroweberPackages\Tax\TaxType  $taxType
     * @return \Illuminate\Http\Response
     */
    public function show(TaxType $taxType)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \MicroweberPackages\Tax\TaxType  $taxType
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $taxType = TaxType::find($request->route('tax_type'));

        return $this->view('tax::admin.taxes.edit',[
            'taxType' => $taxType,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \MicroweberPackages\Tax\TaxType  $taxType
     * @return \Illuminate\Http\Response
     */
    public function update(TaxTypeRequest $request)
    {
        $taxType = TaxType::find($request->route('tax_type'));

        $taxType->name = $request->name;
        $taxType->type = $request->type;
        $taxType->rate = $request->rate;
        $taxType->description = $request->description;
        if ($request->has('collective_tax')) {
            $taxType->collective_tax = $request->collective_tax;
        }
        $taxType->compound_tax = $request->compound_tax;
        $taxType->save();

        return $this->view('tax::admin.taxes.edit',[
            'taxType' => $taxType,
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \MicroweberPackages\Tax\TaxType  $taxType
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {

        $taxType = TaxType::find($request->route('tax_type'));

        if (!$taxType) {
            return redirect(route('tax-types.index'))->with('status', 'Tax not found');
        }

        if ($taxType->taxes() && $taxType->taxes()->count() > 0) {
            return redirect(route('tax-types.index'))->with('status', 'Failed to delete tax.');
        }

        $taxType->delete();

        return redirect(route('tax-types.index'))->with('status', 'Tax has beed deleted.');
    }
}

src/MicroweberPackages/Tax/resources/views/admin/taxes/create.blade.php
@extends('invoice::admin.layout')

@section('title', 'Create New Tax Type')

@section('content')

    <h3>Create New Tax Type</h3>

    <br/>

    @if ($errors->any())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }} <br/>
            @endforeach
        </div><br/>
    @endif

    <form method="post" action="{{ route('tax-types.store') }}">
        @csrf

        <div class="row">

            <div class="col-md-12">
                <div class="form-group">
                    <label>Name:</label>
                    <input type="text" class="form-control" name="name"/>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Prcent:</label>
                    <input type="text" class="form-control" name="percent" value="1.00"/>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group">
                    <label>Description:</label>
                    <textarea class="form-control" name="description"></textarea>
                </div>
            </div>


            <div class="col-md-12">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" name="compound_tax" value="1" class="custom-control-input">
                    <label class="custom-control-label">Compound Tax</label>
                </div>
                <br />
            </div>


        </div>


        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save Tax</button>
    </form>

@endsection

src/MicroweberPackages/Tax/resources/views/admin/taxes/edit.blade.php
@extends('invoice::admin.layout')

@section('content')

    <h3>Edit Tax Type</h3>

    <br/>

    @if ($errors->any())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }} <br/>
            @endforeach
        </div><br/>
    @endif

    <form method="post" action="{{ route('tax-types.update', $taxType->id) }}">

        @method('PATCH')
        @csrf

        <div class="row">

            <div class="col-md-12">
                <div class="form-group">
                    <label>Name:</label>
                    <input type="text" class="form-control" name="name" value="{{ $taxType->name }}"/>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label>Prcent:</label>
                    <input type="text" class="form-control" name="percent" value="{{ $taxType->percent }}"/>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group">
                    <label>Description:</label>
                    <textarea class="form-control" name="description">{{ $taxType->description }}</textarea>
                </div>
            </div>

            <div class="col-md-12">
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" name="compound_tax" value="{{ $taxType->compound_tax }}" class="custom-control-input">
                    <label class="custom-control-label">Compound Tax</label>
                </div>
                <br />
            </div>


        </div>


        <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Update Tax</button>
    </form>

@endsection

src/MicroweberPackages/Tax/resources/views/admin/taxes/index.blade.php
@extends('invoice::admin.layout')

@section('title', 'Tax types')

@section('content')

    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Precent</th>
            <th scope="col">Description</th>
            <th scope="col" colspan="2">Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($taxTypes as $taxType):
        <tr>
            <th scope="row">{{ $taxType->id }}</th>
            <td>{{ $taxType->name }}</td>
            <td>{{ $taxType->percent }}%</td>
            <td>{{ $taxType->description }}</td>
            <td>{{ $taxType->id }}</td>
            <td>
                <a href="{{ route('tax-types.edit',$taxType->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('tax-types.destroy', $taxType->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

@endsection