src/MicroweberPackages/Role/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix(ADMIN_PREFIX)->name('admin.')->namespace('\MicroweberPackages\Role\Http\Controllers\Admin')->group(function () {

    Route::resource('role', 'RolesController');
    Route::resource('user', 'UsersController');

    Route::post('role/clone', [
        'as' => 'role.clone',
        'uses' => 'RolesController@cloneRole'
    ]);

});

src/MicroweberPackages/Role/Http/Controllers/Admin/RolesController.php
<?php

namespace MicroweberPackages\Role\Http\Controllers\Admin;

use MicroweberPackages\App\Http\Controllers\AdminController;
use MicroweberPackages\Role\Repositories\Permission;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use JavaScript;

class RolesController extends AdminController
{
    /**
     * Display a listing of Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $roles = Role::with('users')->get();

        return $this->view('role::admin.roles.index', compact('roles'));
    }

    /**
     * Show the form for creating new Role.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $selectedPermissions = array();
        $permissionGroups = Permission::all();

        return $this->view('role::admin.roles.edit', compact('permissionGroups', 'selectedPermissions'));
    }

    /**
     * Store a newly created Role in storage.
     *
     * @param  \App\Http\Requests\StoreRolesRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles|max:20',
            'permission' => 'required',
        ]);

        $role = Role::create($request->except('permission'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->givePermissionTo($permissions);

        return redirect()->route('roles.index');
    }


    /**
     * Show the form for editing Role.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $permissions = Permission::all();
        $role = Role::findOrFail($id);
        $permissionGroups = Permission::all();

        $selectedPermissions = $role->permissions()->pluck('name')->toArray();

        /*  JavaScript::put([
              'foo' => $selectedPermissions
          ]);*/

        return $this->view('role::admin.roles.edit', compact('role', 'permissions', 'selectedPermissions', 'permissionGroups'));
    }

    /**
     * Update Role in storage.
     *
     * @param  \App\Http\Requests\UpdateRolesRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // TODO

        $request->validate([
            'name' => 'required|max:20',//unique:roles
            'permission' => 'required',
        ]);

        $role = Role::findOrFail($id);
        $role->update($request->except('permission'));
        $permissions = $request->input('permission') ? $request->input('permission') : [];
        $role->syncPermissions($permissions);

        return redirect()->route('roles.index');
    }

    public function cloneRole(Request $request)
    {
        $oldRole = Role::with('permissions')->find($request->id);

        $role = Role::create([
            'name' => $oldRole->name . ' (dublicate)',
        ]);
        $role->givePermissionTo($oldRole->permissions);

        return redirect(route('roles.edit', $role->id))->with('status', 'Role is cloned.');
    }

    /**
     * Remove Role from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index');
    }

    /**
     * Delete all selected Role at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if ($request->input('ids')) {
            $entries = Role::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

src/MicroweberPackages/Role/Http/Controllers/Admin/UsersController.php
<?php

namespace MicroweberPackages\Role\Http\Controllers\Admin;

use MicroweberPackages\App\Http\Controllers\AdminController;
use MicroweberPackages\User\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;

class UsersController extends AdminController
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::all();

        return $this->view('role::admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::get()->pluck('name', 'name');

        return $this->view('role::admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create(array_merge($request->all(), ['status' => 'Active']));
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->assignRole($roles);

        return redirect()->route('users.index');
    }


    /**
     * Show the form for editing User.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $roles = Role::get()->pluck('name', 'name');

        $user = User::findOrFail($id);

        $selectedRoles = $user->roles()->pluck('name');
        /*
                JavaScript::put([
                    'role' => $selectedRoles
                ]);*/

        return $this->view('role::admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update User in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);
        $user->update($request->all());
        $roles = $request->input('roles') ? $request->input('roles') : [];
        $user->syncRoles($roles);

        return redirect()->route('users.index');
    }

    /**
     * Remove User from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index');
    }

    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if ($request->input('ids')) {
            $entries = User::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

src/MicroweberPackages/Role/resources/views/admin/roles/index.blade.php
@extends('admin::layout')

@section('title', 'Manage roles')

@section('icon')
    <i class="mdi mdi-format-list-checks module-icon-svg-fill"></i>
@endsection

@section('content')
    @if (isset($errors) && $errors->any())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }} <br/>
            @endforeach
        </div><br/>
    @endif

    <div class="row d-flex justify-content-end align-items-end mb-4">
        <div class="col-md-6">
            <h5 class="font-weight-bold">User roles list and permitions</h5>
            <small class="text-muted">List of your user roles below</small>
        </div>

        <div class="col-md-6 text-right">
            <a href="{{route('admin.role.create')}}" class="btn btn-success btn-sm"><i class="mdi mdi-book-account"></i> Add New role</a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-hover dataTable js-exportable table-permissions">
            <thead>
            <tr>
                <th style="width:200px;"><?php _e('Role name'); ?></th>
                <th class="text-center"><?php _e('Users'); ?></th>
                <th style="width:300px;" class="text-center"><?php _e('Actions'); ?></th>
            </tr>
            </thead>
           {{-- <tfoot>
            <tr>
                <th style="width: 50px;">ID</th>
                <th style="width:200px;"><?php _e('Role name'); ?></th>
                <th class="text-center"><?php _e('Users'); ?></th>
                <th style="width:300px;" class="text-center"><?php _e('Actions'); ?></th>
            </tr>
            </tfoot>--}}
            <tbody>
            @foreach($roles as $row)
                <tr>
                    <td>{{ $row->name }}</td>
                    <td class="text-center">{{ $row->users->count() }}</td>
                    <td style="width:300px;" class="text-center">
                        <a href="{{route('roles.edit',$row->id)}}" class="btn btn-link btn-sm">Edit</a>

                        <form method="post" action="{{ route('roles.clone') }}" class="d-inline">
                            <input type="hidden" value="{{ $row->id }}" name="id">
                            <button type="submit" class="btn btn-link btn-sm">Dublicate</button>
                        </form>

                        <form id="delete_form" method="POST" action="{{ route('roles.destroy',$row->id) }}" class="d-inline">
                            {{ csrf_field() }}
                            <input name="_method" type="hidden" value="DELETE">
                            <button class="btn btn-link btn-sm text-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection