src/MicroweberPackages/Payment/routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Frontend Routes
|--------------------------------------------------------------------------
|
*/


Route::prefix(ADMIN_PREFIX)->namespace('\MicroweberPackages\Payment\Http\Controllers\Admin')->group(function () {

    Route::post('/payments/delete', [
        'as' => 'payments.delete',
        'uses' => 'PaymentController@delete'
    ]);

    Route::post('/payments/send', [
        'as' => 'payments.send',
        'uses' => 'PaymentController@sendPayment'
    ]);

    Route::resource('payments', 'PaymentController');

});

src/MicroweberPackages/Payment/Http/Controllers/Admin/PaymentController.php
<?php
namespace MicroweberPackages\Payment\Http\Controllers\Admin;

use Illuminate\Http\Request;
use MicroweberPackages\App\Http\Controllers\AdminController;
use MicroweberPackages\Customer\Customer;
use MicroweberPackages\Invoice\Company;
use MicroweberPackages\Payment\Http\Requests\PaymentRequest;
use MicroweberPackages\Invoice\Invoice;
use MicroweberPackages\Payment\Payment;
use MicroweberPackages\Payment\PaymentMethod;
use Carbon\Carbon;
use function MongoDB\BSON\toJSON;
use MicroweberPackages\Invoice\User;
use Validator;
use MicroweberPackages\Invoice\Mail\PaymentPdf;

class PaymentController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $limit = $request->has('limit') ? $request->limit : 10;

        $payments = Payment::with(['customer', 'invoice', 'paymentMethod'])
            ->join('customers', 'customers.id', '=', 'payments.customer_id')
            ->leftJoin('invoices', 'invoices.id', '=', 'payments.invoice_id')
            ->leftJoin('payment_methods', 'payment_methods.id', '=', 'payments.payment_method_id')
            ->applyFilters($request->only([
                'search',
                'payment_number',
                'payment_method_id',
                'customer_id',
                'orderByField',
                'orderBy'
            ]))
           //  ->whereCompany($request->header('company'))
            ->select('payments.*', 'customers.name', 'invoices.invoice_number', 'payment_methods.name as payment_mode')
            ->latest()
            ->paginate($limit);

        return $this->view('payment::admin.payments.index', ['customers'=> Customer::all(), 'paymentMethods'=>PaymentMethod::all(), 'payments'=>$payments]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        // Update Payment Methods
        $paymentOptions = payment_options();
        if (!empty($paymentOptions)) {
            foreach ($paymentOptions as $paymentOption) {
                $findPayment = PaymentMethod::where('name', $paymentOption['name'])->first();
                if (!$findPayment) {
                    PaymentMethod::create([
                        'name'=>$paymentOption['name']
                    ]);
                }
            }
        }
        
        $payment_prefix = 'PAY';//CompanySetting::getSetting('payment_prefix', $request->header('company'));
        $payment_num_auto_generate =1;// CompanySetting::getSetting('payment_auto_generate', $request->header('company'));


        $nextPaymentNumberAttribute = null;
        $nextPaymentNumber = Payment::getNextPaymentNumber($payment_prefix);

        if ($payment_num_auto_generate == "YES") {
            $nextPaymentNumberAttribute = $nextPaymentNumber;
        }

        return $this->view('payment::admin.payments.edit', [
            'payment'=>false,
            'invoices'=> Invoice::all(),
            'customers' => Customer::
            //whereCompany($request->header('company'))
                get(),
            'paymentMethods' => PaymentMethod::
            //whereCompany($request->header('company'))
                latest()
                ->get(),
            'nextPaymentNumberAttribute' => $nextPaymentNumberAttribute,
            'nextPaymentNumber' => $payment_prefix.'-'.$nextPaymentNumber,
            'payment_prefix' => $payment_prefix
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PaymentRequest $request)
    {
        $payment_number = explode("-",$request->payment_number);
        $number_attributes['payment_number'] = $payment_number[0].'-'.sprintf('%06d', intval($payment_number[1]));

        Validator::make($number_attributes, [
            'payment_number' => 'required|unique:payments,payment_number'
        ])->validate();

        $payment_date = Carbon::createFromFormat('Y-m-d', $request->payment_date);

        if ($request->has('invoice_id') && $request->invoice_id != null) {
            $invoice = Invoice::find($request->invoice_id);
            if ($invoice && $invoice->due_amount == $request->amount) {
                $invoice->status = Invoice::STATUS_ORIGINAL;
                $invoice->paid_status = Invoice::STATUS_PAID;
                $invoice->due_amount = 0;
            } elseif ($invoice && $invoice->due_amount != $request->amount) {
                $invoice->due_amount = (int)$invoice->due_amount - (int)$request->amount;
                if ($invoice->due_amount < 0) {
                    return response()->json([
                        'error' => 'invalid_amount'
                    ]);
                }
                $invoice->paid_status = Invoice::STATUS_PARTIALLY_PAID;
            }
            $invoice->save();
        }

        $payment = Payment::create([
            'payment_date' => $payment_date,
            'payment_number' => $number_attributes['payment_number'],
            'customer_id' => $request->customer_id,
            'company_id' => $request->header('company'),
            'invoice_id' => $request->invoice_id,
            'payment_method_id' => $request->payment_method_id,
            'amount' => $request->amount,
            'notes' => $request->notes,
            'unique_hash' => str_random(60)
        ]);

        return redirect(route('payments.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $payment = Payment::with(['customer', 'invoice', 'paymentMethod'])->find($id);

        return response()->json([
            'payment' => $payment,
            'shareable_link' => url('/payments/pdf/'.$payment->unique_hash)
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $payment = Payment::with(['customer', 'invoice', 'paymentMethod'])->find($id);

        $invoices = Invoice::where('paid_status', '<>', Invoice::STATUS_PAID)
            ->where('customer_id', $payment->customer_id)->where('due_amount', '>', 0)
           // ->whereCompany($request->header('company'))
            ->get();

        return $this->view('payment::admin.payments.edit', [
            'invoice_id'=>$id,
            'customers' => Customer::
               // ->whereCompany($request->header('company'))
                get(),
            'paymentMethods' => PaymentMethod::
            //whereCompany($request->header('company'))
                latest()
                ->get(),
            'nextPaymentNumber' => $payment->getPaymentNumAttribute(),
            'payment_prefix' => $payment->getPaymentPrefixAttribute(),
            'shareable_link' => url('/payments/pdf/'.$payment->unique_hash),
            'payment' => $payment,
            'invoices' => $invoices
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PaymentRequest $request, $id)
    {
        $payment_number = explode("-",$request->payment_number);
        $number_attributes['payment_number'] = $payment_number[0].'-'.sprintf('%06d', intval($payment_number[1]));

        Validator::make($number_attributes, [
            'payment_number' => 'required|unique:payments,payment_number'.','.$id
        ])->validate();

        $payment_date = Carbon::createFromFormat('Y-m-d', $request->payment_date);

        $payment = Payment::find($id);
        $oldAmount = $payment->amount;

        if ($request->has('invoice_id') && $request->invoice_id && ($oldAmount != $request->amount)) {
            $amount = (int)$request->amount - (int)$oldAmount;
            $invoice = Invoice::find($request->invoice_id);
            $invoice->due_amount = (int)$invoice->due_amount - (int)$amount;
            if ($invoice->due_amount < 0) {
                return response()->json([
                    'error' => 'invalid_amount'
                ]);
            }

            if ($invoice->due_amount == 0) {
                $invoice->status = Invoice::STATUS_ORIGINAL;
                $invoice->paid_status = Invoice::STATUS_PAID;
            } else {
                $invoice->status = $invoice->getPreviousStatus();
                $invoice->paid_status = Invoice::STATUS_PARTIALLY_PAID;
            }

            $invoice->save();
        }

        $payment->payment_date = $payment_date;
        $payment->payment_number = $number_attributes['payment_number'];
        $payment->customer_id = $request->customer_id;
        $payment->invoice_id = $request->invoice_id;
        $payment->payment_method_id = $request->payment_method_id;
        $payment->amount = $request->amount;
        $payment->notes = $request->notes;
        $payment->save();

        return redirect(route('payments.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $payment = Payment::find($id);

        if ($payment->invoice_id != null) {
            $invoice = Invoice::find($payment->invoice_id);
            $invoice->due_amount = ((int)$invoice->due_amount + (int)$payment->amount);

            if ($invoice->due_amount == $invoice->total) {
                $invoice->paid_status = Invoice::STATUS_UNPAID;
            } else {
                $invoice->paid_status = Invoice::STATUS_PARTIALLY_PAID;
            }

src/MicroweberPackages/Payment/resources/views/admin/payments/edit.blade.php
@extends('invoice::admin.layout')

@if (isset($payment) && $payment)
    @section('title', 'Edit payment')
@else
    @section('title', 'Add new payment')
@endif

@section('content')

    @if ($errors->any())
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                {{ $error }} <br/>
            @endforeach
        </div><br/>
    @endif

    <a href="{{route('payments.index')}}" class="btn btn-outline-primary"><i class="fa fa-list"></i> Back to payments</a>
    <br />
    <br />

    @if(count($invoices)==0)
        <div class="alert alert-success"><i class="fa fa-check"></i> All invoices are payed. Nothing for pay.</div>
    @endif

    @if($payment)
        <form method="post" action="{{ route('payments.update', $payment->id) }}">
            @method('PUT')
            @else
                <form method="post" action="{{ route('payments.store') }}">
                    @endif
                    @csrf
                    <div class="row">


                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Date:</label>
                                <input type="datetime-local" class="form-control"
                                       value="@if($payment){{$payment->payment_date}}@else{{date('Y-m-d')}}@endif"
                                       name="payment_date"/>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Payment Number:</label>
                                <input type="text" class="form-control"
                                       value="@if(isset($payment) && $payment){{ $payment->payment_number }}@else{{ $nextPaymentNumber }} @endif"
                                       name="payment_number"/>
                            </div>
                        </div>


                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Customer:</label>
                                <select class="form-control selectpicker" data-live-search="true" name="customer_id"
                                        placeholder="Start typing something to search customers...">
                                    <option disabled="disabled">Select customer..</option>
                                    @foreach($customers as $customer)
                                        <option @if($payment && $customer->id == $payment->customer_id)selected="selected"
                                                @endif value="{{$customer->id}}">{{$customer->first_name}} {{$customer->last_name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Invoice:</label>
                                <select class="form-control selectpicker" data-live-search="true" name="invoice_id"
                                        placeholder="Start typing something to search invoices...">
                                    @if(count($invoices)==0)
                                        <option>No invoices for paying.</option>
                                    @else
                                    <option>Select invoice..</option>
                                    @endif
                                    @foreach($invoices as $invoice)
                                        <option
                                        @if(request()->get('invoice_id') == $invoice->id)selected="selected"@endif
                                        @if($payment && $invoice->id == $payment->invoice_id)selected="selected"@endif
                                        value="{{$invoice->id}}">
                                            {{$invoice->invoice_number}}
                                        </option>
                                    @endforeach
                                </select>
                                <br/>
                                <br/>
                                @if(count($invoices)> 0)
                                    <div class="alert alert-warning"><i class="fa fa-list"></i> Select invoices wich are not payed.</div>
                               @endif


                            </div>
                        </div>


                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Amount:</label>
                                <div class="form-group">
                                    <div class="input-group mb-3 prepend-transparent append-transparent">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text text-muted">{{ mw()->shop_manager->currency_symbol() }}</span>
                                        </div>
                                        <input type="text" class="form-control" name="amount"
                                               value="@if(isset($payment) && $payment){{ number_format($payment->amount, 2) }}@elseif(request()->get('amount') !== ''){{request()->get('amount')}}@endif"/>
                                        <div class="input-group-append">
                                            <span class="input-group-text" data-toggle="tooltip"
                                                  title="To put a product on sale, makeCompare at price the original price and enter the lower amount into Price."><i
                                                        class="mdi mdi-help-circle"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Payment Method:</label>
                                <select class="form-control selectpicker" data-live-search="true" name="payment_method_id"
                                        placeholder="Start typing something to search customers...">
                                    <option>Select payment method..</option>
                                    @foreach($paymentMethods as $paymentMethod)
                                        <option @if($payment && $paymentMethod->id == $payment->payment_method_id)selected="selected"
                                                @endif value="{{$paymentMethod->id}}">{{$paymentMethod->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>


                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Note:</label>
                                <textarea class="form-control"
                                          name="note">@if(isset($payment) && $payment){{ $payment->note }}@endif</textarea>
                            </div>
                        </div>


                        <div class="col-md-12" style="margin-top:15px;">
                            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Save Payment
                            </button>
                        </div>


                    </div>
                </form>

@endsection

src/MicroweberPackages/Payment/resources/views/admin/payments/index.blade.php
@extends('invoice::admin.layout')

@section('content')

    @if (session('status'))
        <div class="alert alert-success">
           <i class="fa fa-check"></i> {{ session('status') }}
        </div>
    @endif

    <script type="text/javascript">
        $(document).ready(function () {
            $(".js-customers-filter-form").change(function() {
                $('.js-customers-filter-form').submit();
            });
        });
    </script>

    <form method="get" class="js-customers-filter-form">
        <input type="hidden" value="true" name="filter">
        <div class="row">
            <div class="col-md-8">
                <div class="form-inline">
                    <div class="form-group mr-1 mb-2">
                        <label for="inputInvoices2" class="sr-only">Payments</label>
                        <input type="text" name="search" value="@if(request()->get('search')){{request()->get('search')}}@endif" class="form-control" id="inputInvoices2" placeholder="Search Payments..">
                    </div>
                    <button type="submit" class="btn btn-outline-primary btn-icon mb-2"><i class="mdi mdi-magnify"></i> Search</button>
                </div>
            </div>

            @if(request()->get('filter') == 'true')
                <div class="col-md-1">
                    <a href="{{route('customers.index')}}" style="margin-top: 15px" class="btn btn-outline-primary">Filter <i class="fa fa-times"></i></a>
                </div>
            @else
                <div class="col-md-1">
                    <!-- No filter -->
                </div>
            @endif

            <div class="col-md-1">
                <button type="submit" style="margin-top: 15px" class="btn btn-outline-primary">Filter <i class="fa fa-filter"></i></button>
            </div>
            <div class="col-md-2 pull-right">
                <a href="{{ route('payments.create') }}" style="margin-top: 15px"  class="btn btn-primary btn-block"><i class="fa fa-plus"></i> New Payment</a>
            </div>
        </div>
        <div class="invoices-search-box">
            <div class="row">

                <div class="col-md-4">
                    <div class="form-group">
                        <label>Customer</label>
                        <select class="form-control selectpicker" data-live-search="true" name="customer_id"
                                placeholder="Start typing something to search customers...">
                            <option value="">Select customer..</option>
                            @foreach($customers as $customer)
                                <option value="{{$customer->id}}">{{$customer->first_name}} {{$customer->last_name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="col-md-4">
                    <label>Payment Number</label>
                    <input type="text" class="form-control" value="@if(request()->get('payment_number')){{request()->get('payment_number')}}@endif" name="payment_number">
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label>Payment Method:</label>
                        <select class="form-control selectpicker" data-live-search="true" name="payment_method_id"
                                placeholder="Start typing something to search customers...">
                            <option value="">Select payment method..</option>
                            @foreach($paymentMethods as $paymentMethod)
                                <option @if($paymentMethod->id == request()->get('payment_method_id'))selected="selected"
                                        @endif value="{{$paymentMethod->id}}">{{$paymentMethod->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

            </div>
        </div>
    </form>

    <br />
    <br />

    <script type="text/javascript">
        $(document).ready(function () {
            $(".js-select-all").click(function () {
                $("input[type=checkbox]").prop('checked', $(this).prop('checked'));
            });


            $('.js-delete-all').click(function (e) {

                var id = [];
                $("input[name='id']:checked").each (function() {
                    id.push($(this).val());
                });

                $.ajax({
                    type: "POST",
                    url: '{{ route('payments.delete') }}',
                    data: {id:id},
                    success: function(data) {
                        if (data.status == 'success') {
                            window.location = window.location;
                        }
                        if (data.status == 'danger') {
                            $('.actions-messages').html('<div class="alert alert-danger">'+data.message+'</div>');
                        }
                    }
                });
            });
        });
    </script>


    <div class="actions">
        <div class="actions-messages"></div>
        <button class="btn btn-danger js-delete-all"><i class="fa fa-times"></i> Delete all</button>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th>
                <div class="form-group">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input js-select-all" id="customCheck2">
                        <label class="custom-control-label" for="customCheck2"></label>
                    </div>
                </div>
            </th>
            <th style="text-transform: uppercase">Date</th>
            <th style="text-transform: uppercase">Customer</th>
            <th style="text-transform: uppercase">Payment Mode</th>
            <th style="text-transform: uppercase">Payment Number</th>
            <th style="text-transform: uppercase">Invoice</th>
            <th style="text-transform: uppercase">Amount</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach($payments as $payment):
        <tr>
            <th>
                <div class="form-group">
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input js-selected-payment" id="customCheck{{$payment->id}}" name="id" value="{{$payment->id}}">
                        <label class="custom-control-label" for="customCheck{{$payment->id}}"></label>
                    </div>
                </div>
            </th>
            <td>{{ $payment->payment_date }}</td>
            <td>
                {{ $payment->customer->first_name }}
                {{ $payment->customer->last_name }}
            </td>
            <td>
                @if ($payment->paymentMethod)
                {{ $payment->paymentMethod->name }}
                @else
                    No Payment Method
                @endif
            </td>
            <td>{{ $payment->payment_number }}</td>
            <td>{{ $payment->invoice->invoice_number }}</td>
            <td>{{ currency_format($payment->amount) }}</td>
            <td>
                <div class="btn-group">
                    <a type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     Action
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{{ route('payments.edit', $payment->id) }}"><i class="fa fa-pen"></i> &nbsp; Edit</a>
                        <a class="dropdown-item" href="{{ route('payments.show', $payment->id) }}"><i class="fa fa-eye"></i> &nbsp; View</a>

                        <form action="{{ route('payments.destroy', $payment->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="dropdown-item"><i class="fa fa-times"></i> Delete</button>
                        </form>
                    </div>
                </div>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>

</div>
@endsection